#!/usr/bin/env bash
#
# extract-locale-keys.sh
# Extracts every translatable key (the first string literal passed to
# EllesmereUI.L(...) or EllesmereUI.Lf(...)) from the addon source and writes a
# sorted, de-duplicated list to EllesmereUILocales/_keys.txt.
#
# This is the STATIC key list (literals only). Keys passed as variables -- e.g.
# L(cfg.text) -- cannot be seen statically; use the in-game /euiloc harvester for
# the complete runtime set. Together they cover everything.
#
# Usage:  ./.tools/extract-locale-keys.sh        (run from anywhere)
# CI uses this to verify EllesmereUILocales/_keys.txt is current (see locale-check.yml).
#
set -euo pipefail
export LC_ALL=C

# cd to the addon root (parent of .tools/)
cd "$(dirname "$0")/.."

OUT="EllesmereUILocales/_keys.txt"
TMP="$(mktemp)"

grep -rhoE 'EllesmereUI\.Lf?\("[^"]*"' \
  --include='*.lua' \
  --exclude-dir='Libs' \
  --exclude-dir='EllesmereUILocales' \
  --exclude-dir='.release' \
  --exclude='EllesmereUI_LocaleDev.lua' \
  . \
  | sed -E 's/^EllesmereUI\.Lf?\("//; s/"$//' \
  | sort -u > "$TMP"

COUNT="$(wc -l < "$TMP" | tr -d ' ')"

{
  echo "# Auto-generated by .tools/extract-locale-keys.sh -- do not edit by hand."
  echo "# Canonical list of translatable English keys passed as string literals"
  echo "# ($COUNT unique). Regenerate after wrapping new strings. Keys passed as"
  echo "# variables are not listed here -- use the in-game /euiloc harvester for"
  echo "# the complete runtime set."
  cat "$TMP"
} > "$OUT"

rm -f "$TMP"
echo "Wrote $COUNT keys to $OUT"
