if EUI_CLIENT_BLOCKED then return end -- pre-12.1 client failsafe (EllesmereUI_ClientGate.lua)
-------------------------------------------------------------------------------
--  EllesmereUIFriends_RealmGroups.lua
--  Realm -> mini-region lookup tables for friend region detection.
--  Mini regions: namerica, samerica, australia, europe, russia, korea, taiwan, china
--  Full regions: NA (namerica+samerica+australia), EU (europe+russia), KR, TW, CN
-------------------------------------------------------------------------------

local MINI_TO_FULL = {
    namerica  = "NA",
    samerica  = "NA",
    australia  = "NA",
    europe    = "EU",
    russia    = "EU",
    korea     = "KR",
    taiwan    = "TW",
    china     = "CN",
}

local REGION_ID_TO_FULL = {
    [1] = "NA",  -- Americas + Oceania
    [2] = "KR",
    [3] = "EU",  -- Europe + Russia
    [4] = "TW",
    [5] = "CN",
}

-- Region 1: Americas & Oceania
local REALMS_NA = {
["Azralon"] = "samerica",
["Gallywix"] = "samerica",
["Goldrinn"] = "samerica",
["Nemesis"] = "samerica",
["TolBarad"] = "samerica",
["Drakkari"] = "samerica",
["Quel'Thalas"] = "samerica",
["Ragnaros"] = "samerica",
["Loatheb"] = "samerica",
["Aman'Thul"] = "australia",
["Barthilas"] = "australia",
["Caelestrasz"] = "australia",
["Dath'Remar"] = "australia",
["Dreadmaul"] = "australia",
["Frostmourne"] = "australia",
["Gundrak"] = "australia",
["Jubei'Thos"] = "australia",
["Khaz'goroth"] = "australia",
["Nagrand"] = "australia",
["Saurfang"] = "australia",
["Thaurissan"] = "australia",
["Arugal"] = "australia",
["Yojamba"] = "australia",
["Remulos"] = "australia",
["Felstriker"] = "australia",
["Shadowstrike"] = "australia",
["Penance"] = "australia",
["Aegwynn"] = "namerica",
["AeriePeak"] = "namerica",
["Agamaggan"] = "namerica",
["Aggramar"] = "namerica",
["Akama"] = "namerica",
["Alexstrasza"] = "namerica",
["Alleria"] = "namerica",
["AltarofStorms"] = "namerica",
["AlteracMountains"] = "namerica",
["Andorhal"] = "namerica",
["Anetheron"] = "namerica",
["Antonidas"] = "namerica",
["Anub'arak"] = "namerica",
["Anvilmar"] = "namerica",
["Arathor"] = "namerica",
["Archimonde"] = "namerica",
["Area52"] = "namerica",
["ArgentDawn"] = "namerica",
["Arthas"] = "namerica",
["Arygos"] = "namerica",
["Auchindoun"] = "namerica",
["Azgalor"] = "namerica",
["AzjolNerub"] = "namerica",
["Azshara"] = "namerica",
["Azuremyst"] = "namerica",
["Baelgun"] = "namerica",
["Balnazzar"] = "namerica",
["BlackDragonflight"] = "namerica",
["Blackhand"] = "namerica",
["Blackrock"] = "namerica",
["BlackwaterRaiders"] = "namerica",
["BlackwingLair"] = "namerica",
["Blade'sEdge"] = "namerica",
["Bladefist"] = "namerica",
["BleedingHollow"] = "namerica",
["BloodFurnace"] = "namerica",
["Bloodhoof"] = "namerica",
["Bloodscalp"] = "namerica",
["Bonechewer"] = "namerica",
["BoreanTundra"] = "namerica",
["Boulderfist"] = "namerica",
["Bronzebeard"] = "namerica",
["BurningBlade"] = "namerica",
["BurningLegion"] = "namerica",
["Cairne"] = "namerica",
["CenarionCircle"] = "namerica",
["Cenarius"] = "namerica",
["Cho'gall"] = "namerica",
["Chromaggus"] = "namerica",
["Coilfang"] = "namerica",
["Crushridge"] = "namerica",
["Daggerspine"] = "namerica",
["Dalaran"] = "namerica",
["Dalvengyr"] = "namerica",
["DarkIron"] = "namerica",
["Darkspear"] = "namerica",
["Darrowmere"] = "namerica",
["Dawnbringer"] = "namerica",
["Deathwing"] = "namerica",
["DemonSoul"] = "namerica",
["Dentarg"] = "namerica",
["Destromath"] = "namerica",
["Dethecus"] = "namerica",
["Detheroc"] = "namerica",
["Doomhammer"] = "namerica",
["Draenor"] = "namerica",
["Dragonblight"] = "namerica",
["Dragonmaw"] = "namerica",
["Drenden"] = "namerica",
["Dunemaul"] = "namerica",
["Durotan"] = "namerica",
["Duskwood"] = "namerica",
["EarthenRing"] = "namerica",
["EchoIsles"] = "namerica",
["Eitrigg"] = "namerica",
["Eldre'Thalas"] = "namerica",
["Elune"] = "namerica",
["EmeraldDream"] = "namerica",
["Eonar"] = "namerica",
["Eredar"] = "namerica",
["Executus"] = "namerica",
["Exodar"] = "namerica",
["Farstriders"] = "namerica",
["Feathermoon"] = "namerica",
["Fenris"] = "namerica",
["Firetree"] = "namerica",
["Fizzcrank"] = "namerica",
["Frostmane"] = "namerica",
["Frostwolf"] = "namerica",
["Galakrond"] = "namerica",
["Garithos"] = "namerica",
["Garona"] = "namerica",
["Garrosh"] = "namerica",
["Ghostlands"] = "namerica",
["Gilneas"] = "namerica",
["Gnomeregan"] = "namerica",
["Gorefiend"] = "namerica",
["Gorgonnash"] = "namerica",
["Greymane"] = "namerica",
["GrizzlyHills"] = "namerica",
["Gul'dan"] = "namerica",
["Gurubashi"] = "namerica",
["Hakkar"] = "namerica",
["Haomarush"] = "namerica",
["Hellscream"] = "namerica",
["Hydraxis"] = "namerica",
["Hyjal"] = "namerica",
["Icecrown"] = "namerica",
["Illidan"] = "namerica",
["Jaedenar"] = "namerica",
["Kael'thas"] = "namerica",
["Kalecgos"] = "namerica",
["Kargath"] = "namerica",
["Kel'Thuzad"] = "namerica",
["Khadgar"] = "namerica",
["KhazModan"] = "namerica",
["Kil'jaeden"] = "namerica",
["Kilrogg"] = "namerica",
["KirinTor"] = "namerica",
["Korgath"] = "namerica",
["Korialstrasz"] = "namerica",
["KulTiras"] = "namerica",
["LaughingSkull"] = "namerica",
["Lethon"] = "namerica",
["Lightbringer"] = "namerica",
["Lightning'sBlade"] = "namerica",
["Lightninghoof"] = "namerica",
["Llane"] = "namerica",
["Lothar"] = "namerica",
["Madoran"] = "namerica",
["Maelstrom"] = "namerica",
["Magtheridon"] = "namerica",
["Maiev"] = "namerica",
["Mal'Ganis"] = "namerica",
["Malfurion"] = "namerica",
["Malorne"] = "namerica",
["Malygos"] = "namerica",
["Mannoroth"] = "namerica",
["Medivh"] = "namerica",
["Misha"] = "namerica",
["Mok'Nathal"] = "namerica",
["MoonGuard"] = "namerica",
["Moonrunner"] = "namerica",
["Mug'thol"] = "namerica",
["Muradin"] = "namerica",
["Nathrezim"] = "namerica",
["Nazgrel"] = "namerica",
["Nazjatar"] = "namerica",
["Ner'zhul"] = "namerica",
["Nesingwary"] = "namerica",
["Nordrassil"] = "namerica",
["Norgannon"] = "namerica",
["Onyxia"] = "namerica",
["Perenolde"] = "namerica",
["Proudmoore"] = "namerica",
["Quel'dorei"] = "namerica",
["Ravencrest"] = "namerica",
["Ravenholdt"] = "namerica",
["Rexxar"] = "namerica",
["Rivendare"] = "namerica",
["Runetotem"] = "namerica",
["Sargeras"] = "namerica",
["ScarletCrusade"] = "namerica",
["Scilla"] = "namerica",
["Sen'jin"] = "namerica",
["Sentinels"] = "namerica",
["ShadowCouncil"] = "namerica",
["Shadowmoon"] = "namerica",
["Shadowsong"] = "namerica",
["Shandris"] = "namerica",
["ShatteredHalls"] = "namerica",
["ShatteredHand"] = "namerica",
["Shu'halo"] = "namerica",
["SilverHand"] = "namerica",
["Silvermoon"] = "namerica",
["SistersofElune"] = "namerica",
["Skullcrusher"] = "namerica",
["Skywall"] = "namerica",
["Smolderthorn"] = "namerica",
["Spinebreaker"] = "namerica",
["Spirestone"] = "namerica",
["Staghelm"] = "namerica",
["SteamwheedleCartel"] = "namerica",
["Stonemaul"] = "namerica",
["Stormrage"] = "namerica",
["Stormreaver"] = "namerica",
["Stormscale"] = "namerica",
["Suramar"] = "namerica",
["Tanaris"] = "namerica",
["Terenas"] = "namerica",
["Terokkar"] = "namerica",
["TheForgottenCoast"] = "namerica",
["TheScryers"] = "namerica",
["TheUnderbog"] = "namerica",
["TheVentureCo"] = "namerica",
["ThoriumBrotherhood"] = "namerica",
["Thrall"] = "namerica",
["Thunderhorn"] = "namerica",
["Thunderlord"] = "namerica",
["Tichondrius"] = "namerica",
["Tortheldrin"] = "namerica",
["Trollbane"] = "namerica",
["Turalyon"] = "namerica",
["TwistingNether"] = "namerica",
["Uldaman"] = "namerica",
["Uldum"] = "namerica",
["Undermine"] = "namerica",
["Ursin"] = "namerica",
["Uther"] = "namerica",
["Vashj"] = "namerica",
["Vek'nilash"] = "namerica",
["Velen"] = "namerica",
["Warsong"] = "namerica",
["Whisperwind"] = "namerica",
["Wildhammer"] = "namerica",
["Windrunner"] = "namerica",
["Winterhoof"] = "namerica",
["WyrmrestAccord"] = "namerica",
["Ysera"] = "namerica",
["Ysondre"] = "namerica",
["Zangarmarsh"] = "namerica",
["Zul'jin"] = "namerica",
["Zuluhed"] = "namerica",
["Ashkandi"] = "namerica",
["Atiesh"] = "namerica",
["Benediction"] = "namerica",
["BloodsailBuccaneers"] = "namerica",
["Faerlina"] = "namerica",
["Grobbulus"] = "namerica",
["Mankrik"] = "namerica",
["OldBlanchy"] = "namerica",
["Westfall"] = "namerica",
["Whitemane"] = "namerica",
["ChaosBolt"] = "namerica",
["CrusaderStrike"] = "namerica",
["DefiasPillager"] = "namerica",
["Doomhowl"] = "namerica",
["Dreamscythe"] = "namerica",
["LavaLash"] = "namerica",
["LivingFlame"] = "namerica",
["LoneWolf"] = "namerica",
["Nightslayer"] = "namerica",
["Pagle"] = "namerica",
["SkullRock"] = "namerica",
["WildGrowth"] = "namerica",
["Maladath"] = "australia",
}

-- Region 3: Europe & Russia
local REALMS_EU = {
["Aegwynn"] = "europe",
["Alexstrasza"] = "europe",
["Alleria"] = "europe",
["Ambossar"] = "europe",
["Aman'Thul"] = "europe",
["Antonidas"] = "europe",
["Anub'arak"] = "europe",
["Area52"] = "europe",
["Arthas"] = "europe",
["Arygos"] = "europe",
["Azshara"] = "europe",
["Baelgun"] = "europe",
["Blackhand"] = "europe",
["Blackmoore"] = "europe",
["Blackrock"] = "europe",
["Blutkessel"] = "europe",
["Dalvengyr"] = "europe",
["DasKonsortium"] = "europe",
["DasSyndikat"] = "europe",
["DerMithrilorden"] = "europe",
["DerRatvonDalaran"] = "europe",
["Destromath"] = "europe",
["Dethecus"] = "europe",
["DieAldor"] = "europe",
["DieArguswacht"] = "europe",
["DieewigeWacht"] = "europe",
["DieNachtwache"] = "europe",
["DieSilberneHand"] = "europe",
["DieTodeskrallen"] = "europe",
["DunMorogh"] = "europe",
["Echsenkessel"] = "europe",
["Eredar"] = "europe",
["Everlook"] = "europe",
["FestungderStürme"] = "europe",
["Forscherliga"] = "europe",
["Frostmourne"] = "europe",
["Frostwolf"] = "europe",
["Garrosh"] = "europe",
["Gilneas"] = "europe",
["Gorgonnash"] = "europe",
["Gul'dan"] = "europe",
["Kargath"] = "europe",
["Kel'Thuzad"] = "europe",
["Khaz'goroth"] = "europe",
["Kil'jaeden"] = "europe",
["Krag'jin"] = "europe",
["Lothar"] = "europe",
["Madmortem"] = "europe",
["Mal'Ganis"] = "europe",
["Malfurion"] = "europe",
["Malorne"] = "europe",
["Malygos"] = "europe",
["Mannoroth"] = "europe",
["Mug'thol"] = "europe",
["Nathrezim"] = "europe",
["Nazjatar"] = "europe",
["Nera'thor"] = "europe",
["Nethersturm"] = "europe",
["Norgannon"] = "europe",
["Nozdormu"] = "europe",
["Onyxia"] = "europe",
["Perenolde"] = "europe",
["Proudmoore"] = "europe",
["Rajaxx"] = "europe",
["Rexxar"] = "europe",
["Sen'jin"] = "europe",
["Shattrath"] = "europe",
["Shen'dralar"] = "europe",
["SteamwheedleCartel"] = "europe",
["Taerar"] = "europe",
["Teldrassil"] = "europe",
["Terrordar"] = "europe",
["Theradras"] = "europe",
["Thrall"] = "europe",
["Tichondrius"] = "europe",
["Tirion"] = "europe",
["Todeswache"] = "europe",
["Ulduar"] = "europe",
["Un'Goro"] = "europe",
["Vek'lor"] = "europe",
["Venoxis"] = "europe",
["Wrathbringer"] = "europe",
["Ysera"] = "europe",
["ZirkeldesCenarius"] = "europe",
["Zuluhed"] = "europe",
["Arak-arahm"] = "europe",
["Arathi"] = "europe",
["Archimonde"] = "europe",
["Auberdine"] = "europe",
["Chantséternels"] = "europe",
["Cho'gall"] = "europe",
["Chromaggus"] = "europe",
["ConfrérieduThorium"] = "europe",
["ConseildesOmbres"] = "europe",
["CulteDeLaRiveNoire"] = "europe",
["Dalaran"] = "europe",
["Drek'Thar"] = "europe",
["Eitrigg"] = "europe",
["Eldre'Thalas"] = "europe",
["Elune"] = "europe",
["Garona"] = "europe",
["Hyjal"] = "europe",
["Illidan"] = "europe",
["Kael'thas"] = "europe",
["KhazModan"] = "europe",
["KirinTor"] = "europe",
["Krasus"] = "europe",
["LaCroisadeécarlate"] = "europe",
["LesClairvoyants"] = "europe",
["LesSentinelles"] = "europe",
["MarécagedeZangar"] = "europe",
["Medivh"] = "europe",
["Naxxramas"] = "europe",
["Ner'zhul"] = "europe",
["Rashgarroth"] = "europe",
["Sargeras"] = "europe",
["Sinstralis"] = "europe",
["Suramar"] = "europe",
["Templenoir"] = "europe",
["Throk'Feroth"] = "europe",
["Uldaman"] = "europe",
["Varimathras"] = "europe",
["Vol'jin"] = "europe",
["Ysondre"] = "europe",
["C'Thun"] = "europe",
["ColinasPardas"] = "europe",
["DunModr"] = "europe",
["Exodar"] = "europe",
["LosErrantes"] = "europe",
["Mandokir"] = "europe",
["Minahonda"] = "europe",
["Sanguino"] = "europe",
["Shen'dralar"] = "europe",
["Tyrande"] = "europe",
["Uldum"] = "europe",
["Zul'jin"] = "europe",
["Nemesis"] = "europe",
["Pozzodell'Eternità"] = "europe",
["Aggra"] = "europe",
["GrimBatol"] = "europe",
["Ashenvale"] = "russia",
["Azuregos"] = "russia",
["Blackscar"] = "russia",
["BootyBay"] = "russia",
["BoreanTundra"] = "russia",
["Chromie"] = "russia",
["Deathguard"] = "russia",
["Deepholm"] = "russia",
["Eversong"] = "russia",
["Flamegor"] = "russia",
["Fordragon"] = "russia",
["Galakrond"] = "russia",
["Goldrinn"] = "russia",
["Gordunni"] = "russia",
["Grommash"] = "russia",
["HowlingFjord"] = "russia",
["LichKing"] = "russia",
["MoltenCore"] = "russia",
["Razuvious"] = "russia",
["Soulflayer"] = "russia",
["Theradras"] = "russia",
["Thermaplugg"] = "russia",
["Wyrmthalak"] = "russia",
["Agamaggan"] = "europe",
["Aggramar"] = "europe",
["Ahn'Qiraj"] = "europe",
["Al'Akir"] = "europe",
["Alonsus"] = "europe",
["Anachronos"] = "europe",
["Arathor"] = "europe",
["ArgentDawn"] = "europe",
["Aszune"] = "europe",
["Auchindoun"] = "europe",
["AzjolNerub"] = "europe",
["Azuremyst"] = "europe",
["Balnazzar"] = "europe",
["Blade'sEdge"] = "europe",
["Bladefist"] = "europe",
["Bloodfeather"] = "europe",
["Bloodhoof"] = "europe",
["Bloodscalp"] = "europe",
["Boulderfist"] = "europe",
["Bronzebeard"] = "europe",
["BronzeDragonflight"] = "europe",
["BurningBlade"] = "europe",
["BurningLegion"] = "europe",
["BurningSteppes"] = "europe",
["ChamberofAspects"] = "europe",
["Chromaggus"] = "europe",
["Crushridge"] = "europe",
["Daggerspine"] = "europe",
["DarkmoonFaire"] = "europe",
["Darksorrow"] = "europe",
["Darkspear"] = "europe",
["Deathwing"] = "europe",
["DefiasBrotherhood"] = "europe",
["Dentarg"] = "europe",
["Doomhammer"] = "europe",
["Draenor"] = "europe",
["Dragonblight"] = "europe",
["Dragonmaw"] = "europe",
["Drak'thul"] = "europe",
["Dunemaul"] = "europe",
["EarthenRing"] = "europe",
["EmeraldDream"] = "europe",
["Emeriss"] = "europe",
["Eonar"] = "europe",
["Executus"] = "europe",
["Frostmane"] = "europe",
["Frostwhisper"] = "europe",
["Genjuros"] = "europe",
["Ghostlands"] = "europe",
["GrimBatol"] = "europe",
["Hakkar"] = "europe",
["Haomarush"] = "europe",
["Hellfire"] = "europe",
["Hellscream"] = "europe",
["Jaedenar"] = "europe",
["Karazhan"] = "europe",
["Kazzak"] = "europe",
["Khadgar"] = "europe",
["Kilrogg"] = "europe",
["Kor'gall"] = "europe",
["KulTiras"] = "europe",
["LaughingSkull"] = "europe",
["Lightbringer"] = "europe",
["Lightning'sBlade"] = "europe",
["Magtheridon"] = "europe",
["Mazrigos"] = "europe",
["Moonglade"] = "europe",
["Nagrand"] = "europe",
["Neptulon"] = "europe",
["Nordrassil"] = "europe",
["Outland"] = "europe",
["Quel'Thalas"] = "europe",
["Ragnaros"] = "europe",
["Ravencrest"] = "europe",
["Ravenholdt"] = "europe",
["Runetotem"] = "europe",
["Saurfang"] = "europe",
["ScarshieldLegion"] = "europe",
["Shadowsong"] = "europe",
["ShatteredHalls"] = "europe",
["ShatteredHand"] = "europe",
["Silvermoon"] = "europe",
["Skullcrusher"] = "europe",
["Spinebreaker"] = "europe",
["Sporeggar"] = "europe",
["Stormrage"] = "europe",
["Stormreaver"] = "europe",
["Stormscale"] = "europe",
["Sunstrider"] = "europe",
["Sylvanas"] = "europe",
["Talnivarr"] = "europe",
["TarrenMill"] = "europe",
["Terenas"] = "europe",
["Terokkar"] = "europe",
["TheMaelstrom"] = "europe",
["TheSha'tar"] = "europe",
["TheVentureCo"] = "europe",
["Thunderhorn"] = "europe",
["Trollbane"] = "europe",
["Turalyon"] = "europe",
["Twilight'sHammer"] = "europe",
["TwistingNether"] = "europe",
["Vashj"] = "europe",
["Vek'nilash"] = "europe",
["Wildhammer"] = "europe",
["Xavius"] = "europe",
["Zenedar"] = "europe",
["Firemaw"] = "europe",
["Gehennas"] = "europe",
["Golemagg"] = "europe",
["MirageRaceway"] = "europe",
["Mograine"] = "europe",
["Nek'Rosh"] = "europe",
["PyrewoodVillage"] = "europe",
["Soulseeker"] = "europe",
["Spineshatter"] = "europe",
["Stitches"] = "europe",
["Thunderstrike"] = "europe",
["WildGrowth"] = "europe",
["ZandalarTribe"] = "europe",
}

-- Regions 2, 4, 5: Korea, Taiwan, China
local REALMS_ASIA = {
["AbyssalMaw"] = "china",
["AeriePeakCN"] = "china",
["Akil'zon"] = "china",
["Algalon"] = "china",
["Chronos"] = "china",
["Goldshire"] = "china",
["LichKing"] = "china",
["Onyxia"] = "china",
["SilverHand"] = "china",
["SilvermoonCN"] = "china",
["TitanReforged"] = "china",
["Azshara"] = "korea",
["BurningLegion"] = "korea",
["Cenarius"] = "korea",
["Deathwing"] = "korea",
["Durotan"] = "korea",
["Frostmourne"] = "korea",
["Hellscream"] = "korea",
["Hyjal"] = "korea",
["Ragnaros"] = "korea",
["Windrunner"] = "korea",
["Zul'jin"] = "korea",
["Arthas"] = "taiwan",
["Arygos"] = "taiwan",
["BleedingHollow"] = "taiwan",
["ChillwindPoint"] = "taiwan",
["CrystalpineStinger"] = "taiwan",
["DemonFallCanyon"] = "taiwan",
["Dragonmaw"] = "taiwan",
["Frostmane"] = "taiwan",
["Global"] = "taiwan",
["Icecrown"] = "taiwan",
["KrolBlade"] = "taiwan",
["Light'sHope"] = "taiwan",
["Menethil"] = "taiwan",
["Nightsong"] = "taiwan",
["OldBlanchy"] = "taiwan",
["OrderoftheCloudSerpent"] = "taiwan",
["Quel'dorei"] = "taiwan",
["Shadowmoon"] = "taiwan",
["Skywall"] = "taiwan",
["Spirestone"] = "taiwan",
["Stormscale"] = "taiwan",
["WorldTree"] = "taiwan",
["Whisperwind"] = "taiwan",
["Wrathbringer"] = "taiwan",
["ZealotBlade"] = "taiwan",
}

local REGION_ICON_PATH = "Interface\\AddOns\\EllesmereUIFriends\\Media\\regions\\"

-- Lookup a realm name -> mini region realmName should have spaces removed
local function GetRealmMiniRegion(realmName)
    if not realmName or realmName == "" then return nil end
    local clean = realmName:gsub("%s+", "")
    -- Check player's own region table first (handles overlapping realm names)
    local myRegion = GetCurrentRegion()
    local primary, secondary
    if myRegion == 3 then
        primary, secondary = REALMS_EU, REALMS_NA
    elseif myRegion == 2 or myRegion == 4 or myRegion == 5 then
        primary, secondary = REALMS_ASIA, REALMS_NA
    else
        primary, secondary = REALMS_NA, REALMS_EU
    end
    return primary[clean] or secondary[clean] or REALMS_ASIA[clean]
end

-- Get the mini region for a BNet friend's game account
local function GetFriendMiniRegion(gameAccountInfo)
    if not gameAccountInfo then return nil end
    -- Try realmName first
    local realm = gameAccountInfo.realmName
    if realm and realm ~= "" then
        local result = GetRealmMiniRegion(realm)
        if result then return result end
    end
    -- Fallback: parse richPresence ("Zone - Realm" format)
    -- If realmName was empty, the friend is likely cross-region, so check OTHER tables first
    local rich = gameAccountInfo.richPresence
    if rich and rich ~= "" then
        local realmFromRich = rich:match("%s%-%s(.+)$")
        if realmFromRich and realmFromRich ~= "" then
            local clean = realmFromRich:gsub("%s+", "")
            local myRegion = GetCurrentRegion()
            -- Check the opposite region first since empty realmName = cross-region friend
            if myRegion == 1 then
                return REALMS_EU[clean] or REALMS_ASIA[clean] or REALMS_NA[clean]
            elseif myRegion == 3 then
                return REALMS_NA[clean] or REALMS_ASIA[clean] or REALMS_EU[clean]
            else
                return REALMS_NA[clean] or REALMS_EU[clean] or REALMS_ASIA[clean]
            end
        end
    end
    return nil
end

-- Get the full region for a mini region
local function GetFullRegion(miniRegion)
    return miniRegion and MINI_TO_FULL[miniRegion]
end

-- Get the player's own full region
local function GetMyFullRegion()
    return REGION_ID_TO_FULL[GetCurrentRegion()] or "NA"
end

-- Get the icon path for a mini region
local function GetRegionIcon(miniRegion)
    if not miniRegion then return nil end
    return REGION_ICON_PATH .. miniRegion .. ".png"
end

-- Public API
EllesmereUI.GetRealmMiniRegion = GetRealmMiniRegion
EllesmereUI.GetFriendMiniRegion = GetFriendMiniRegion
EllesmereUI.GetFullRegion = GetFullRegion
EllesmereUI.GetMyFullRegion = GetMyFullRegion
EllesmereUI.GetRegionIcon = GetRegionIcon
EllesmereUI.MINI_TO_FULL = MINI_TO_FULL
